### ISSUE TITLE
Slighly scaled (blurred) images in modal

### ISSUE THREAD

**Issue by szepeviktor** [jonnymccullagh/munstrap#10]
Please add

``` css
@media (min-width:992px){
.modal-lg {width:940px !important;}
}
```
